kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resource-locker-operator
subjects:
- kind: ServiceAccount
  name: resource-locker-operator
  namespace: resource-locker-operator 
roleRef:
  kind: ClusterRole
  name: resource-locker-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: resource-locker-operator
subjects: 
- kind: ServiceAccount
  name: resource-locker-operator
roleRef:
  kind: Role
  name: resource-locker-operator
  apiGroup: rbac.authorization.k8s.io